In [59]:
import pandas as pd
import numpy as np
# from sklearn.preprocessing import MinMaxScaler
# from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler
# from sklearn.naive_bayes import GaussianNB
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.tree import DecisionTreeClassifier
import math
import operator
import random
# from sklearn.model_selection import KFold
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')

In [2]:
data_spam = pd.read_csv("C:/Users/mouni/Downloads/SML/HW4/spambase.data")

In [3]:
data_spam = data_spam.rename(columns={'0':'word_freq_make','0.64':'word_freq_address',
                                      '0.64.1':'word_freq_all','0.1':'word_freq_3d',
                                      '0.32':'word_freq_our','0.2':'word_freq_over',
                                      '0.3':'word_freq_remove','0.4':'word_freq_internet',
                                      '0.5':'word_freq_order','0.6':'word_freq_mail',
                                      '0.7':'word_freq_receive','0.64.2':'word_freq_will','0.8':'word_freq_people',
                                      '0.9':'word_freq_report','0.10':'word_freq_addresses','0.32.1':'word_freq_free',
                                      '0.11':'word_freq_business','1.29':'word_freq_email',
                                      '1.93':'word_freq_you','0.12':'word_freq_credit','0.96':'word_freq_your',
                                      '0.13':'word_freq_font','0.14':'word_freq_000','0.15':'word_freq_money',
                                      '0.16':'word_freq_hp','0.17':'word_freq_hpl','0.18':'word_freq_george',
                                      '0.19':'word_freq_650','0.20':'word_freq_lab','0.21':'word_freq_labs',
                                      '0.22':'word_freq_telnet','0.23':'word_freq_857','0.24':'word_freq_data',
                                      '0.25':'word_freq_415','0.26':'word_freq_85','0.27':'word_freq_technology',
                                      '0.28':'word_freq_1999','0.29':'word_freq_parts','0.30':'word_freq_pm',
                                      '0.31':'word_freq_direct','0.32.2':'word_freq_cs','0.33':'word_freq_meeting',
                                      '0.34':'word_freq_original','0.35':'word_freq_project','0.36':'word_freq_re',
                                      '0.37':'word_freq_edu','0.38':'word_freq_table','0.39':'word_freq_conference',
                                      '0.40':'char_freq_semicolon','0.41':'char_freq_leftparen',
                                      '0.42':'char_freq_leftsquare','0.778':'char_freq_bang',
                                      '0.43':'char_freq_dollar','0.44':'char_freq_hash',
                                      '3.756':'capital_run_length_average','61':'capital_run_length_longest',
                                      '278':'capital_run_length_total','1':'is_spam'})

In [4]:
data_y = data_spam['is_spam']
data_x = data_spam.drop(columns = ['is_spam'])
data_x.shape

(4600, 57)

In [5]:
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(data_x)
data_scaled.shape

(4600, 57)

In [6]:
df = pd.DataFrame(data=data_scaled[:,0:],
                  index=data_scaled[:,0],
                  columns=['word_freq_make', 'word_freq_address','word_freq_all', 'word_freq_3d', 'word_freq_our',
                           'word_freq_over', 'word_freq_remove', 'word_freq_internet','word_freq_order', 'word_freq_mail',
                           'word_freq_receive','word_freq_will', 'word_freq_people', 'word_freq_report',
                           'word_freq_addresses', 'word_freq_free', 'word_freq_business','word_freq_email',
                           'word_freq_you', 'word_freq_credit', 'word_freq_your','word_freq_font', 'word_freq_000',
                           'word_freq_money', 'word_freq_hp','word_freq_hpl', 'word_freq_george', 'word_freq_650',
                           'word_freq_lab','word_freq_labs', 'word_freq_telnet', 'word_freq_857', 'word_freq_data',
                           'word_freq_415', 'word_freq_85', 'word_freq_technology', 'word_freq_1999','word_freq_parts',
                           'word_freq_pm', 'word_freq_direct', 'word_freq_cs','word_freq_meeting', 'word_freq_original',
                           'word_freq_project', 'word_freq_re', 'word_freq_edu', 'word_freq_table',
                           'word_freq_conference', 'char_freq_semicolon', 'char_freq_leftparen', 'char_freq_leftsquare',
                           'char_freq_bang', 'char_freq_dollar', 'char_freq_hash','capital_run_length_average',
                           'capital_run_length_longest', 'capital_run_length_total'])

### Problem 1 [Ensemble classifiers]

**Use the SPAMBASE dataset for this problem. Split the original data into 75% for training and 25% for
testing (chosen at random).**

In [7]:
xTrain, xTest, yTrain, yTest = train_test_split(df, data_y, test_size = 0.25, random_state = 0)

**(a) Use an existing package to train an AdaBoost algorithm with 10, 50, and 100 base classifiers. Use a
decision tree as the base classification model. Report accuracy, error, precision, and recall on both the
training and testing sets.**

In [44]:
Adaboost_model1 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),
                                    n_estimators=10)
fit1 = Adaboost_model1.fit(xTrain,yTrain)
AdaBoost_pred1 = Adaboost_model1.predict(xTest)

In [45]:
Acc = metrics.accuracy_score(yTest, AdaBoost_pred1)
print("Accuracy for AdaBoost with base classifier 10: ",Acc)
print("Error:", 1-Acc)
print("\n",metrics.classification_report(yTest, AdaBoost_pred1))

Accuracy for AdaBoost with base classifier 10:  0.9269565217391305
Error: 0.07304347826086954

               precision    recall  f1-score   support

           0       0.93      0.96      0.94       692
           1       0.93      0.88      0.91       458

    accuracy                           0.93      1150
   macro avg       0.93      0.92      0.92      1150
weighted avg       0.93      0.93      0.93      1150



In [53]:
cm = metrics.confusion_matrix(yTest, AdaBoost_pred1)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[661  31]
 [ 53 405]]

Accuracy: 0.9269565217391305
Recall: 0.8842794759825328
Precision: 0.9288990825688074
Error: 0.07304347826086954
F1 score: 0.906040268456376


In [46]:
Adaboost_model2 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),
                                    n_estimators=50)
fit2 = Adaboost_model2.fit(xTrain,yTrain)
AdaBoost_pred2 = Adaboost_model2.predict(xTest)

In [47]:
Acc2 = metrics.accuracy_score(yTest, AdaBoost_pred2)
print("Accuracy for AdaBoost with base classifier 50: ",Acc2)
print("Error:", 1-Acc2)
print("\n",metrics.classification_report(yTest, AdaBoost_pred2))

Accuracy for AdaBoost with base classifier 50:  0.9452173913043478
Error: 0.05478260869565221

               precision    recall  f1-score   support

           0       0.95      0.96      0.95       692
           1       0.93      0.93      0.93       458

    accuracy                           0.95      1150
   macro avg       0.94      0.94      0.94      1150
weighted avg       0.95      0.95      0.95      1150



In [55]:
cm = metrics.confusion_matrix(yTest, AdaBoost_pred2)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[661  31]
 [ 32 426]]

Accuracy: 0.9452173913043478
Recall: 0.9301310043668122
Precision: 0.9321663019693655
Error: 0.05478260869565221
F1 score: 0.9311475409836065


In [48]:
Adaboost_model3 = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),
                                    n_estimators=100)
fit3 = Adaboost_model3.fit(xTrain,yTrain)
AdaBoost_pred3 = Adaboost_model3.predict(xTest)

In [49]:
Acc3 = metrics.accuracy_score(yTest, AdaBoost_pred3)
print("Accuracy for AdaBoost with base classifier 100: ",Acc3)
print("Error:", 1-Acc3)
print("\n",metrics.classification_report(yTest, AdaBoost_pred3))

Accuracy for AdaBoost with base classifier 100:  0.9495652173913044
Error: 0.050434782608695605

               precision    recall  f1-score   support

           0       0.96      0.96      0.96       692
           1       0.93      0.94      0.94       458

    accuracy                           0.95      1150
   macro avg       0.95      0.95      0.95      1150
weighted avg       0.95      0.95      0.95      1150



In [56]:
cm = metrics.confusion_matrix(yTest, AdaBoost_pred3)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[661  31]
 [ 27 431]]

Accuracy: 0.9495652173913044
Recall: 0.9410480349344978
Precision: 0.9329004329004329
Error: 0.050434782608695605
F1 score: 0.9369565217391305


**(b) Use an existing package to train a Random Forest algorithm with 10, 50, and 100 decision trees.
Report similar metrics on both the training and testing sets.**

In [63]:
Rand_model1 = RandomForestClassifier(n_estimators=10)
fit_rand1 = Rand_model1.fit(xTrain,yTrain)
Rand_pred1 = Rand_model1.predict(xTest)

In [64]:
Acc = metrics.accuracy_score(yTest, Rand_pred1)
print("Accuracy for AdaBoost with base classifier 10: ",Acc)
print("Error:", 1-Acc)
print("\n",metrics.classification_report(yTest, Rand_pred1))

Accuracy for AdaBoost with base classifier 10:  0.9521739130434783
Error: 0.047826086956521685

               precision    recall  f1-score   support

           0       0.95      0.97      0.96       692
           1       0.96      0.92      0.94       458

    accuracy                           0.95      1150
   macro avg       0.95      0.95      0.95      1150
weighted avg       0.95      0.95      0.95      1150



In [65]:
cm = metrics.confusion_matrix(yTest, Rand_pred1)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[673  19]
 [ 36 422]]

Accuracy: 0.9521739130434783
Recall: 0.9213973799126638
Precision: 0.9569160997732427
Error: 0.047826086956521685
F1 score: 0.9388209121245829


In [66]:
Rand_model2 = RandomForestClassifier(n_estimators=50)
fit_rand2 = Rand_model2.fit(xTrain,yTrain)
Rand_pred2 = Rand_model2.predict(xTest)

In [67]:
Acc1 = metrics.accuracy_score(yTest, Rand_pred2)
print("Accuracy for AdaBoost with base classifier 50: ",Acc1)
print("Error:", 1-Acc1)
print("\n",metrics.classification_report(yTest, Rand_pred2))

Accuracy for AdaBoost with base classifier 50:  0.957391304347826
Error: 0.042608695652173956

               precision    recall  f1-score   support

           0       0.95      0.98      0.97       692
           1       0.96      0.93      0.95       458

    accuracy                           0.96      1150
   macro avg       0.96      0.95      0.96      1150
weighted avg       0.96      0.96      0.96      1150



In [68]:
cm = metrics.confusion_matrix(yTest, Rand_pred2)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[676  16]
 [ 33 425]]

Accuracy: 0.957391304347826
Recall: 0.9279475982532751
Precision: 0.963718820861678
Error: 0.042608695652173956
F1 score: 0.9454949944382647


In [69]:
Rand_model3 = RandomForestClassifier(n_estimators=100)
fit_rand3 = Rand_model3.fit(xTrain,yTrain)
Rand_pred3 = Rand_model3.predict(xTest)

In [70]:
Acc2 = metrics.accuracy_score(yTest, Rand_pred3)
print("Accuracy for AdaBoost with base classifier 100: ",Acc2)
print("Error:", 1-Acc2)
print("\n",metrics.classification_report(yTest, Rand_pred3))

Accuracy for AdaBoost with base classifier 100:  0.9521739130434783
Error: 0.047826086956521685

               precision    recall  f1-score   support

           0       0.95      0.97      0.96       692
           1       0.95      0.93      0.94       458

    accuracy                           0.95      1150
   macro avg       0.95      0.95      0.95      1150
weighted avg       0.95      0.95      0.95      1150



In [71]:
cm = metrics.confusion_matrix(yTest, Rand_pred3)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("\nAccuracy:", ACC)

# Recall
recall = TP/(TP+FN)
print("Recall:", recall)

# Precision 
precision = TP/(TP+FP)
print("Precision:", precision)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((precision*recall)/(precision+recall))
print("F1 score:", f1)

[[669  23]
 [ 32 426]]

Accuracy: 0.9521739130434783
Recall: 0.9301310043668122
Precision: 0.9487750556792873
Error: 0.047826086956521685
F1 score: 0.9393605292171996


**(c) Compare AdaBoost with Random Forest for 10, 50, and 100 base learners based on these results.**

### Problem 2 [AdaBoost classifier] 
**In this exercise, you will implement the AdaBoost algorithm using decision stumps as weak learners.**

**(a) Implement a decision stump classifier that splits on a single feature. You may use any method for
finding the splitting feature and threshold as long as the decision stub performs better than random.**