In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [2]:
data_spam = pd.read_csv("C:/Users/mouni/Downloads/SML/HW3/spambase/spambase.data")

In [24]:
data_spam = data_spam.rename(columns={'0':'word_freq_make','0.64':'word_freq_address',
                                      '0.64.1':'word_freq_all','0.1':'word_freq_3d',
                                      '0.32':'word_freq_our','0.2':'word_freq_over',
                                      '0.3':'word_freq_remove','0.4':'word_freq_internet',
                                      '0.5':'word_freq_order','0.6':'word_freq_mail',
                                      '0.7':'word_freq_receive','0.64.2':'word_freq_will','0.8':'word_freq_people',
                                      '0.9':'word_freq_report','0.10':'word_freq_addresses','0.32.1':'word_freq_free',
                                      '0.11':'word_freq_business','1.29':'word_freq_email',
                                      '1.93':'word_freq_you','0.12':'word_freq_credit','0.96':'word_freq_your',
                                      '0.13':'word_freq_font','0.14':'word_freq_000','0.15':'word_freq_money',
                                      '0.16':'word_freq_hp','0.17':'word_freq_hpl','0.18':'word_freq_george',
                                      '0.19':'word_freq_650','0.20':'word_freq_lab','0.21':'word_freq_labs',
                                      '0.22':'word_freq_telnet','0.23':'word_freq_857','0.24':'word_freq_data',
                                      '0.25':'word_freq_415','0.26':'word_freq_85','0.27':'word_freq_technology',
                                      '0.28':'word_freq_1999','0.29':'word_freq_parts','0.30':'word_freq_pm',
                                      '0.31':'word_freq_direct','0.32.2':'word_freq_cs','0.33':'word_freq_meeting',
                                      '0.34':'word_freq_original','0.35':'word_freq_project','0.36':'word_freq_re',
                                      '0.37':'word_freq_edu','0.38':'word_freq_table','0.39':'word_freq_conference',
                                      '0.40':'char_freq_semicolon','0.41':'char_freq_leftparen',
                                      '0.42':'char_freq_leftsquare','0.778':'char_freq_bang',
                                      '0.43':'char_freq_dollar','0.44':'char_freq_hash',
                                      '3.756':'capital_run_length_average','61':'capital_run_length_longest',
                                      '278':'capital_run_length_total','1':'is_spam'})

In [25]:
data_spam

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
0               0.21               0.28           0.50           0.0   
1               0.06               0.00           0.71           0.0   
2               0.00               0.00           0.00           0.0   
3               0.00               0.00           0.00           0.0   
4               0.00               0.00           0.00           0.0   
5               0.00               0.00           0.00           0.0   
6               0.00               0.00           0.00           0.0   
7               0.15               0.00           0.46           0.0   
8               0.06               0.12           0.77           0.0   
9               0.00               0.00           0.00           0.0   
10              0.00               0.00           0.25           0.0   
11              0.00               0.69           0.34           0.0   
12              0.00               0.00           0.00           0.0   
13              0.00               0.00           1.42           0.0   
14              0.00               0.42           0.42           0.0   
15              0.00               0.00           0.00           0.0   
16              0.00               0.00           0.00           0.0   
17              0.00               0.00           0.55           0.0   
18              0.00               0.63           0.00           0.0   
19              0.00               0.00           0.00           0.0   
20              0.05               0.07           0.10           0.0   
21              0.00               0.00           0.00           0.0   
22              0.00               0.00           0.00           0.0   
23              0.00               0.00           0.00           0.0   
24              0.05               0.07           0.10           0.0   
25              0.00               0.00           0.00           0.0   
26              0.00               0.00           0.00           0.0   
27              0.00               0.00           0.00           0.0   
28              0.00               0.00           0.00           0.0   
29              1.17               0.00           0.00           0.0   
...              ...                ...            ...           ...   
4570            0.00               0.00           0.46           0.0   
4571            0.00               0.00           0.00           0.0   
4572            0.00               0.00           0.18           0.0   
4573            0.29               0.00           0.29           0.0   
4574            0.00               0.00           0.00           0.0   
4575            0.00               0.00           0.00           0.0   
4576            0.00               0.00           1.20           0.0   
4577            0.00               0.00           0.40           0.0   
4578            0.27               0.05           0.10           0.0   
4579            0.00               0.00           0.00           0.0   
4580            0.00               0.00           0.00           0.0   
4581            0.00               0.00           0.00           0.0   
4582            0.00               0.00           1.23           0.0   
4583            0.00               0.00           0.45           0.0   
4584            0.00               0.00           0.00           0.0   
4585            0.00               0.00           0.00           0.0   
4586            0.00               0.00           0.00           0.0   
4587            0.00               0.00           3.03           0.0   
4588            0.00               0.00           0.00           0.0   
4589            0.00               0.00           0.00           0.0   
4590            0.00               0.00           0.00           0.0   
4591            0.00               0.00           1.25           0.0   
4592            0.00               0.00           0.00           0.0   
4593            0.00               0.00       

In [5]:
data_y = data_spam['is_spam']
data_x = data_spam.drop(columns = ['is_spam'])
data_x.shape

(4600, 57)

In [6]:
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(data_x)
data_scaled.shape

(4600, 57)

In [7]:
df = pd.DataFrame(data=data_scaled[:,0:],
                  index=data_scaled[:,0],
                  columns=['word_freq_make', 'word_freq_address','word_freq_all', 'word_freq_3d', 'word_freq_our',
                           'word_freq_over', 'word_freq_remove', 'word_freq_internet','word_freq_order', 'word_freq_mail',
                           'word_freq_receive','word_freq_will', 'word_freq_people', 'word_freq_report',
                           'word_freq_addresses', 'word_freq_free', 'word_freq_business','word_freq_email',
                           'word_freq_you', 'word_freq_credit', 'word_freq_your','word_freq_font', 'word_freq_000',
                           'word_freq_money', 'word_freq_hp','word_freq_hpl', 'word_freq_george', 'word_freq_650',
                           'word_freq_lab','word_freq_labs', 'word_freq_telnet', 'word_freq_857', 'word_freq_data',
                           'word_freq_415', 'word_freq_85', 'word_freq_technology', 'word_freq_1999','word_freq_parts',
                           'word_freq_pm', 'word_freq_direct', 'word_freq_cs','word_freq_meeting', 'word_freq_original',
                           'word_freq_project', 'word_freq_re', 'word_freq_edu', 'word_freq_table',
                           'word_freq_conference', 'char_freq_semicolon', 'char_freq_leftparen', 'char_freq_leftsquare',
                           'char_freq_bang', 'char_freq_dollar', 'char_freq_hash','capital_run_length_average',
                           'capital_run_length_longest', 'capital_run_length_total'])

In [8]:
xTrain, xTest, yTrain, yTest = train_test_split(df, data_y, test_size = 0.25, random_state = 0)

In [9]:
logisticRegr = LogisticRegression()
fit1 = logisticRegr.fit(xTrain, yTrain)
fit1

C:\Users\mouni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [10]:
predictions = logisticRegr.predict(xTest)

In [11]:
cm = metrics.confusion_matrix(yTest, predictions)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

[[656  36]
 [ 45 413]]


In [12]:
score = logisticRegr.score(xTest, yTest)
print(score)

0.9295652173913044


In [13]:
print(metrics.classification_report(yTest, predictions))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94       692
           1       0.92      0.90      0.91       458

    accuracy                           0.93      1150
   macro avg       0.93      0.92      0.93      1150
weighted avg       0.93      0.93      0.93      1150



In [14]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9295652173913044
Recall: 0.9017467248908297
Precision: 0.9198218262806236
Error: 0.07043478260869562
F1 score: 0.9106945975744211


In [15]:
fit1.coef_

array([[-0.11025964, -0.2421029 ,  0.0744696 ,  1.00509894,  0.32554939,
         0.19228165,  0.92593544,  0.19723677,  0.12351767,  0.06294884,
        -0.10617344, -0.15743851,  0.03537821,  0.0268677 ,  0.28783505,
         0.95061687,  0.40331579,  0.06210778,  0.15550624,  0.38409911,
         0.25433162,  0.21443443,  0.79562219,  0.14887934, -2.27372541,
        -0.8708625 , -3.96469735,  0.24012464, -1.00747867, -0.07162933,
        -1.88766095, -0.07221077, -0.51984058,  0.0187023 , -1.0567242 ,
         0.3471644 ,  0.03334317,  0.05257299, -0.31556135, -0.09045731,
        -1.70289729, -1.47481818, -0.1690304 , -0.77961417, -0.79855884,
        -1.3190043 , -0.18852476, -0.91685298, -0.29457888, -0.00719737,
        -0.1671911 ,  0.23197986,  1.14918891,  0.71332883,  2.06528337,
         1.76808093,  0.39388566]])

In [16]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.5

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[ 36 656]
 [413  45]]


In [17]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9295652173913044
Recall: 0.9479768786127167
Precision: 0.9358059914407989
Error: 0.07043478260869562
F1 score: 0.9418521177315148


In [18]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.25

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[ 15 677]
 [363  95]]


In [19]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9043478260869565
Recall: 0.9783236994219653
Precision: 0.8769430051813472
Error: 0.09565217391304348
F1 score: 0.924863387978142


In [20]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.75

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[101 591]
 [445  13]]


In [21]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9008695652173913
Recall: 0.8540462427745664
Precision: 0.9784768211920529
Error: 0.09913043478260875
F1 score: 0.912037037037037


In [22]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.9

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[228 464]
 [455   3]]


In [23]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.7991304347826087
Recall: 0.6705202312138728
Precision: 0.9935760171306209
Error: 0.2008695652173913
F1 score: 0.8006902502157032


In [ ]:
# def sigmoid(z):
#     return 1 / (1 + np.exp(-z))

# z = np.dot(X, theta)
# h = sigmoid(z)

In [31]:
def gradient_descent(X,y,theta,alpha,n):
    
    m = len(y)
        
    for i in range(n):
        prediction = np.dot(X,theta)
        h = 1 / (1 + np.exp(-prediction))
        theta = theta - (1/m) * alpha * (X.T.dot(h - y))
        
    return theta

In [29]:
xTrain.shape

(3450, 57)

In [30]:
yTrain.shape

(3450,)

In [32]:
alpha = 0.01
iter = [10,50,100]
cols = xTrain.columns
theta = np.random.randn(len(cols),1)
theta_df = theta
for i in iter:
    theta_j = gradient_descent(xTrain,yTrain,theta_df,alpha,i)
    yTest_pred_gd = xTest.dot(theta_j)
    print("mean squared error on scaled test data (GD):",mean_squared_error(yTest,yTest_pred_gd))

Exception: Data must be 1-dimensional

### 2

In [34]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
a = nb.fit(xTrain, yTrain)
y_pred = nb.predict(xTest)

ValueError: Input X must be non-negative