In [98]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [22]:
data_spam = pd.read_csv("C:/Users/mouni/Downloads/SML/HW3/spambase/spambase.data")

In [99]:
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(data_spam)

In [100]:
df = pd.DataFrame(data=data_scaled[:,0:],
                  index=data_scaled[:,0],
                  columns=['word_freq_make', 'word_freq_address','word_freq_all', 'word_freq_3d', 'word_freq_our',
 'word_freq_over', 'word_freq_remove', 'word_freq_internet','word_freq_order', 'word_freq_mail',
 'word_freq_receive','word_freq_will', 'word_freq_people', 'word_freq_report',
 'word_freq_addresses', 'word_freq_free', 'word_freq_business','word_freq_email',
 'word_freq_you', 'word_freq_credit', 'word_freq_your','word_freq_font', 'word_freq_000',
 'word_freq_money', 'word_freq_hp','word_freq_hpl', 'word_freq_george', 'word_freq_650', 'word_freq_lab',
 'word_freq_labs', 'word_freq_telnet', 'word_freq_857', 'word_freq_data','word_freq_415', 'word_freq_85',
 'word_freq_technology', 'word_freq_1999','word_freq_parts', 'word_freq_pm', 'word_freq_direct',
 'word_freq_cs','word_freq_meeting', 'word_freq_original', 'word_freq_project', 'word_freq_re',
 'word_freq_edu', 'word_freq_table', 'word_freq_conference', 'char_freq_semicolon',
 'char_freq_leftparen', 'char_freq_leftsquare', 'char_freq_bang', 'char_freq_dollar',
 'char_freq_hash','capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total', 'is_spam'])


# ['word_freq_make', 'word_freq_address','word_freq_all', 'word_freq_3d', 'word_freq_our',
#  'word_freq_over', 'word_freq_remove', 'word_freq_internet','word_freq_order', 'word_freq_mail',
#  'word_freq_receive','word_freq_will', 'word_freq_people', 'word_freq_report',
#  'word_freq_addresses', 'word_freq_free', 'word_freq_business','word_freq_email',
#  'word_freq_you', 'word_freq_credit', 'word_freq_your','word_freq_font', 'word_freq_000',
#  'word_freq_money', 'word_freq_hp','word_freq_hpl', 'word_freq_george', 'word_freq_650', 'word_freq_lab',
#  'word_freq_labs', 'word_freq_telnet', 'word_freq_857', 'word_freq_data','word_freq_415', 'word_freq_85',
#  'word_freq_technology', 'word_freq_1999','word_freq_parts', 'word_freq_pm', 'word_freq_direct',
#  'word_freq_cs','word_freq_meeting', 'word_freq_original', 'word_freq_project', 'word_freq_re',
#  'word_freq_edu', 'word_freq_table', 'word_freq_conference', 'char_freq_semicolon',
#  'char_freq_leftparen', 'char_freq_leftsquare', 'char_freq_bang', 'char_freq_dollar',
#  'char_freq_hash','capital_run_length_average', 'capital_run_length_longest', 'capital_run_length_total', 'is_spam']

In [50]:
data_spam = data_spam.rename(columns={'0':'word_freq_make',
                          '0.64':'word_freq_address',
                          '0.64.1':'word_freq_all',
                          '0.1':'word_freq_3d',
                          '0.32':'word_freq_our',
                          '0.2':'word_freq_over',
                          '0.3':'word_freq_remove',
                          '0.4':'word_freq_internet',
                          '0.5':'word_freq_order',
                          '0.6':'word_freq_mail',
                          '0.7':'word_freq_receive',
                          '0.64.2':'word_freq_will',
                          '0.8':'word_freq_people',
                          '0.9':'word_freq_report',
                          '0.10':'word_freq_addresses',
                          '0.32.1':'word_freq_free',
                          '0.11':'word_freq_business',
                          '1.29':'word_freq_email',
                          '1.93':'word_freq_you',
                          '0.12':'word_freq_credit',
                          '0.96':'word_freq_your',
                          '0.13':'word_freq_font',
                          '0.14':'word_freq_000',
                          '0.15':'word_freq_money',
                          '0.16':'word_freq_hp',
                          '0.17':'word_freq_hpl',
                          '0.18':'word_freq_george',
                          '0.19':'word_freq_650',
                          '0.20':'word_freq_lab',
                          '0.21':'word_freq_labs',
                          '0.22':'word_freq_telnet',
                          '0.23':'word_freq_857',
                          '0.24':'word_freq_data',
                          '0.25':'word_freq_415',
                          '0.26':'word_freq_85',
                          '0.27':'word_freq_technology',
                          '0.28':'word_freq_1999',
                          '0.29':'word_freq_parts',
                          '0.30':'word_freq_pm',
                          '0.31':'word_freq_direct',
                          '0.32.2':'word_freq_cs',
                          '0.33':'word_freq_meeting',
                          '0.34':'word_freq_original',
                          '0.35':'word_freq_project',
                          '0.36':'word_freq_re',
                          '0.37':'word_freq_edu',
                          '0.38':'word_freq_table',
                          '0.39':'word_freq_conference',
                          '0.40':'char_freq_semicolon',
                          '0.41':'char_freq_leftparen',
                          '0.42':'char_freq_leftsquare',
                          '0.778':'char_freq_bang',
                          '0.43':'char_freq_dollar',
                          '0.44':'char_freq_hash',
                          '3.756':'capital_run_length_average',
                          '61':'capital_run_length_longest',
                          '278':'capital_run_length_total',
                          '1':'is_spam'})

In [104]:
xTrain, xTest, yTrain, yTest = train_test_split(df, df.iloc[:,-1], test_size = 0.25, random_state = 0)

In [105]:
xTrain = xTrain.drop(columns = ['is_spam'])
xTest = xTest.drop(columns = ['is_spam'])

In [107]:
df.shape

(4600, 58)

In [108]:
df.head()

word_freq_make  word_freq_address  word_freq_all  word_freq_3d  \
 0.345252        0.345252           0.051976       0.435261     -0.046905   
-0.145982       -0.145982          -0.164984       0.851833     -0.046905   
-0.342475       -0.342475          -0.164984      -0.556576     -0.046905   
-0.342475       -0.342475          -0.164984      -0.556576     -0.046905   
-0.342475       -0.342475          -0.164984      -0.556576     -0.046905   

           word_freq_our  word_freq_over  word_freq_remove  \
 0.345252      -0.256087        0.672259          0.244655   
-0.145982       1.364700        0.343576          0.193562   
-0.342475       0.472524       -0.350309          0.500124   
-0.342475       0.472524       -0.350309          0.500124   
-0.342475       2.286616       -0.350309         -0.291828   

           word_freq_internet  word_freq_order  word_freq_mail  ...  \
 0.345252           -0.088058        -0.323341        1.086529  ...   
-0.145982            0.036609         1.973754        0.016339  ...   
-0.342475            1.308212         0.789315        0.605719  ...   
-0.342475            1.308212         0.789315        0.605719  ...   
-0.342475            4.350087        -0.323341       -0.371410  ...   

           char_freq_semicolon  char_freq_leftparen  char_freq_leftsquare  \
 0.345252            -0.158471            -0.026117             -0.155215   
-0.145982            -0.117398             0.014571             -0.155215   
-0.342475            -0.158471            -0.007622             -0.155215   
-0.342475            -0.158471            -0.015020             -0.155215   
-0.342475            -0.158471             0.310487             -0.155215   

           char_freq_bang  char_freq_dollar  char_freq_hash  \
 0.345252        0.126330          0.423674        0.008739   
-0.145982        0.008631          0.439942       -0.079768   
-0.342475       -0.161788         -0.308392       -0.103060   
-0.342475       -0.164240         -0.308392       -0.103060   
-0.342475       -0.329755         -0.308392       -0.103060   

           capital_run_length_average  capital_run_length_longest  \
 0.345252                   -0.002453                    0.250546   
-0.145982                    0.145895                    2.220875   
-0.342475                   -0.052154                   -0.062450   
-0.342475                   -0.052154                   -0.062450   
-0.342475                   -0.069079                   -0.190726   

           capital_run_length_total   is_spam  
 0.345252                  1.228189  1.240416  
-0.145982                  3.258376  1.240416  
-0.342475                 -0.152207  1.240416  
-0.342475                 -0.152207  1.240416  
-0.342475                 -0.378150  1.240416  

[5 rows x 58 columns]

In [71]:
logisticRegr = LogisticRegression()
fit1 = logisticRegr.fit(xTrain, yTrain)
fit1

C:\Users\mouni\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
predictions = logisticRegr.predict(xTest)

In [63]:
cm = metrics.confusion_matrix(yTest, predictions)
print(cm)
TN = cm[0][0]
FN = cm[1][0]
FP = cm[0][1]
TP = cm[1][1]

[[659  33]
 [ 39 419]]


In [58]:
score = logisticRegr.score(xTest, yTest)
print(score)

0.9373913043478261


In [61]:
print(metrics.classification_report(yTest, predictions))

              precision    recall  f1-score   support

           0       0.94      0.95      0.95       692
           1       0.93      0.91      0.92       458

    accuracy                           0.94      1150
   macro avg       0.94      0.93      0.93      1150
weighted avg       0.94      0.94      0.94      1150



In [69]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9373913043478261
Recall: 0.9148471615720524
Precision: 0.9269911504424779
Error: 0.06260869565217386
F1 score: 0.9208791208791209


In [72]:
fit1.coef_

array([[-3.89705119e-01, -1.74935550e-01,  1.71570781e-01,
         8.95280705e-01,  5.15046824e-01,  8.16289595e-01,
         2.08980476e+00,  5.39606591e-01,  6.26567932e-01,
         5.81491034e-02, -4.78114083e-01, -1.97107263e-01,
         2.04675029e-01,  6.95789812e-02,  1.13322547e+00,
         1.18778391e+00,  8.71963206e-01,  1.31239460e-01,
         8.78347403e-02,  8.82517127e-01,  1.86309085e-01,
         1.14773478e-01,  1.93366508e+00,  3.14887478e-01,
        -1.58094140e+00, -9.37479661e-01, -3.22726694e+00,
         4.11610783e-01, -1.29779737e+00, -1.50744047e-01,
        -1.85373154e+00,  1.15866574e-01, -8.71732847e-01,
         2.01353476e-01, -1.51435200e+00,  7.76156125e-01,
        -2.85505738e-02,  1.45338841e-01, -7.30478283e-01,
        -7.29581313e-01, -1.47706489e+00, -1.83036465e+00,
        -6.15666584e-01, -1.21494604e+00, -7.28492138e-01,
        -1.53169016e+00, -6.83330306e-01, -1.58345273e+00,
        -1.00316044e+00, -4.25317998e-02, -6.69305936e-0

In [85]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.5

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[ 33 659]
 [419  39]]


In [86]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9373913043478261
Recall: 0.9523121387283237
Precision: 0.9441260744985673
Error: 0.06260869565217386
F1 score: 0.9482014388489208


In [89]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.25

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[ 14 678]
 [363  95]]


In [90]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.9052173913043479
Recall: 0.9797687861271677
Precision: 0.8771021992238034
Error: 0.09478260869565214
F1 score: 0.9255972696245733


In [93]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.75

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[105 587]
 [447  11]]


In [94]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.8991304347826087
Recall: 0.8482658959537572
Precision: 0.9816053511705686
Error: 0.10086956521739132
F1 score: 0.910077519379845


In [95]:
prediction_T = logisticRegr.predict_proba(xTest)>= 0.9

prediction_T = prediction_T[:,0]
cm = metrics.confusion_matrix(yTest, prediction_T)
print(cm)
TN = cm[1][0]
FN = cm[0][0]
FP = cm[1][1]
TP = cm[0][1]


[[216 476]
 [455   3]]


In [96]:
# Overall accuracy
ACC = (TP+TN)/(TP+FP+FN+TN)
print("Accuracy:", ACC)

# Sensitivity, hit rate, recall, or true positive rate
TPR = TP/(TP+FN)
print("Recall:", TPR)

# Specificity or true negative rate
TNR = TN/(TN+FP) 

# Precision or positive predictive value
PPV = TP/(TP+FP)
print("Precision:", PPV)

# Error
print("Error:", 1-ACC)

# F1 Score
f1 = 2*((PPV*TPR)/(PPV+TPR))
print("F1 score:", f1)

Accuracy: 0.8095652173913044
Recall: 0.6878612716763006
Precision: 0.9937369519832986
Error: 0.19043478260869562
F1 score: 0.8129803586678054
